# This content is generated by {GENERATOR}
load("@rules_pkg//toolchains/rpm:rpmbuild.bzl", "rpmbuild_toolchain")

rpmbuild_toolchain(
    name = "rpmbuild_auto",
    path = "{RPMBUILD_PATH}",
    version = "{RPMBUILD_VERSION}",
)

toolchain(
    name = "rpmbuild_auto_toolchain",
    toolchain = ":rpmbuild_auto",
    toolchain_type = "@rules_pkg//toolchains/rpm:rpmbuild_toolchain_type",
)
